// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bosen/pkg/auth"
)

// Injectors from wire.go:

func InitializeAuthSessAction() *auth.AuthenticateSessionAction {
	authService := auth.NewAuthService()
	authenticateSessionAction := auth.NewAuthSessAction(authService)
	return authenticateSessionAction
}

func InitializeAuthResource() *auth.AuthResource {
	authenticateSessionAction := InitializeAuthSessAction()
	authResource := auth.NewAuthResource(authenticateSessionAction)
	return authResource
}
