// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bosen/application"
	log2 "bosen/log"
	"bosen/pkg/auth"
	"bosen/pkg/auth/login"
	"bosen/pkg/database"
	"bosen/pkg/user"
	"github.com/emicklei/go-restful/v3"
	"github.com/google/wire"
	"github.com/sourcegraph/log"
)

// Injectors from wire.go:

func InjectLogger() log.Logger {
	logger := log2.ProvideLogger()
	return logger
}

func InjectConfig() application.Config {
	logger := InjectLogger()
	config := application.ProvideConfig(logger)
	return config
}

func InjectDbConfig() database.DbConfig {
	config := InjectConfig()
	dbConfig := config.Database
	return dbConfig
}

func InjectContainer() *restful.Container {
	container := restful.NewContainer()
	return container
}

func InjectDiagnosticResource() *application.DiagnosticResource {
	logger := InjectLogger()
	diagnosticResource := application.NewDiagnosticResource(logger)
	return diagnosticResource
}

func InjectLoginAction() *login.LoginAction {
	dbConfig := InjectDbConfig()
	db := database.ProvideDatabase(dbConfig)
	userRepositoryImpl := user.NewUserRepositoryImpl(db)
	config := InjectConfig()
	loginPresenterImpl := login.NewLoginPresenter(config)
	loginServiceImpl := login.NewLoginServiceImpl(userRepositoryImpl, loginPresenterImpl)
	loginAction := login.NewLoginAction(loginServiceImpl)
	return loginAction
}

func InjectAuthResource() *auth.AuthResource {
	dbConfig := InjectDbConfig()
	db := database.ProvideDatabase(dbConfig)
	userRepositoryImpl := user.NewUserRepositoryImpl(db)
	config := InjectConfig()
	loginPresenterImpl := login.NewLoginPresenter(config)
	loginServiceImpl := login.NewLoginServiceImpl(userRepositoryImpl, loginPresenterImpl)
	loginAction := login.NewLoginAction(loginServiceImpl)
	authResource := auth.NewAuthResource(loginAction)
	return authResource
}

// wire.go:

var DatabaseSet = wire.NewSet(
	InjectDbConfig, database.ProvideDatabase,
)

// UserRepositorySet provides `user.UserRepository` (an interface)
// This can be done by binding interface.
// See: https://github.com/google/wire/blob/main/docs/guide.md#binding-interfaces
var UserRepositorySet = wire.NewSet(
	DatabaseSet, user.NewUserRepositoryImpl, wire.Bind(new(user.UserRepository), new(*user.UserRepositoryImpl)),
)

var LoginPresenterSet = wire.NewSet(
	InjectConfig, login.NewLoginPresenter, wire.Bind(new(login.LoginPresenter), new(*login.LoginPresenterImpl)),
)

var LoginServiceSet = wire.NewSet(
	UserRepositorySet,
	LoginPresenterSet, login.NewLoginServiceImpl, wire.Bind(new(login.LoginService), new(*login.LoginServiceImpl)),
)

var LoginActionSet = wire.NewSet(LoginServiceSet, login.NewLoginAction)

var AuthResourceSet = wire.NewSet(LoginActionSet, auth.NewAuthResource)
